# need 4 gpus

project: coconut
save_path: /data/nlp/coconut-main/checkpoint
name: gsm-Noshared-cross_attn-gating

only_eval: False

coconut: True
shared_para: False
cot: False
no_thoughts: False
no_cot: False

state_combination_method: cross_attention # continuous_only; adapter; cross_attention; projection
combination_use_gating: True

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: True

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: /data/nlp/coconut-main/checkpoint/gsm-cot/checkpoint_6
seed: 0
resume: 3
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True
batch_size_training: 16
debug: False
gradient_accumulation_steps: 2
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01