# need 4 gpus

project: coconut
save_path: /data/nlp/coconut-main/checkpoint
name: gsm-no-cot

only_eval: True

coconut: False
cot: False
no_thoughts: False
no_cot: True

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: openai-community/gpt2
# model_id: meta-llama/Llama-3.2-3B-Instruct
load_model_path: /data/nlp/coconut-main/checkpoint/gsm-no-cot/checkpoint_14
seed: 0
resume: 0

bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_test.json
reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01
